package com.gundam.unicorn.entity;

import com.gundam.unicorn.utils.annotation.FieldNotBlank;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.util.Date;

/**
 * 用户实体类（框架使用说明类）
 * @author kampf
 * @date 2019/08/16 18：49
 */
@Data
public class Person extends BaseEntity{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.PERSON_NAME
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人员名名称")
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.PERSON_CODE
     *
     * @mbg.generated
     */
    @FieldNotBlank(name = "personCode")
    @ApiModelProperty(value = "人员代码", required = true)
    private String personCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.LIST_TYPE
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人员类别")
    private String listType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.SEX
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人员性别")
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.BIRTHDAY
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人员生日")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.ADDERS
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人员地址")
    private String adders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.PHONE
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "联系方式一")
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.PHONE_TWO
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "联系方式二")
    private String phoneTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.PLATE_NUMBER
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "车牌号码")
    private String plateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.FACE_IMG
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人脸图片")
    private String faceImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.FACE_ID
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "人脸识别id")
    private String faceId;

    @ApiModelProperty(value = "角色id")
    private String roleId;

    @ApiModelProperty(value = "角色名称")
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.DEPT_CODE
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "部门编号")
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.DEPT_NAME
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "部门名称")
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_person.VALIDDATE
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "有效日期")
    private Date validDate;

    /**
     * 添加初始化默认值
     */
    public Person(){
        this.personName = "呵呵";
    }

    @Override
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(super.toString());
        sb.append(", personName").append(personName);
        sb.append(", personCode").append(personCode);
        sb.append(", listType").append(listType);
        sb.append(", sex").append(sex);
        sb.append(", birthday").append(birthday);
        sb.append(", phone").append(phone);
        sb.append(", phoneTwo").append(phoneTwo);
        sb.append(", plateNumber").append(plateNumber);
        sb.append(", faceImg").append(faceImg);
        sb.append(", faceId").append(faceId);
        sb.append(", validDate").append(validDate);
        sb.append("]");
        return  sb.toString();
    }
}