package com.gundam.unicorn.entity;

import lombok.Data;

import java.util.Date;

@Data
public class User extends BaseEntity {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_User.User_Name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_User.User_Password
     *
     * @mbg.generated
     */
    private String userPassword;

    private String roleId;

    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_User.Face_Icon
     *
     * @mbg.generated
     */
    private String faceIcon;


    @Override
    public String toString(){
        StringBuffer sb = new StringBuffer();
        sb.append("{");
        sb.append(super.toString());
        sb.append(", userName:").append(userName);
        sb.append(", userPassword:").append(userPassword);
        sb.append(", roleId:").append(roleId);
        sb.append(", roleName:").append(roleName);
        sb.append(", faceIcon:").append(faceIcon);
        return sb.toString();
    }
}