server:
  port: 8080
  servlet:
    context-path: /unicorn
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    name: admin
    url: jdbc:mysql://127.0.0.1:3306/unicorn?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
    include: unicorn
  application:
    name: unicorn-yml


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.gundam.unicorn.entity


logging:
  level:
    root: INFO
    com.gundam.unicorn: DEBUG